name: Deploy Website

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "Host 192.116.98.97\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\tIdentityFile ~/.ssh/deploy_key" > ~/.ssh/config

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/deploy_key idobk@192.116.98.97 "echo SSH connection successful"
        
      - name: Deploy to server
        run: |
          rsync -avz --delete ./ idobk@192.116.98.97:/var/www/w88/
